name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps:
      - name: سحب
        uses: actions/checkout@v3

      - name: تثبيت التبعيات
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          flake8 .

      - name: تشغيل اختبارات الوحدة
        run: |
          nosetests